name: Test the Door

on:
  pull_request:
    branches:
      - door

env:
  GRADLE_OPTS: -Dorg.gradle.daemon=false

jobs:
  test:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17
      - name: Run unit tests
        uses: gradle/gradle-build-action@v2
        with:
          gradle-home-cache-cleanup: true
          arguments: :plugins:scanners:dos:test
